version: '3.9'

services:
  frontend:
    build:
      context: frontend
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - 80:80
    depends_on:
    - backend

  backend:
    build: backend
    ports:
      - 8000:8000
